begin;
create table public.management_report_snapshots(
 id uuid primary key default gen_random_uuid(),report_type text not null check(report_type in('operational','finance','corporate','management')),
 period_start date not null,period_end date not null check(period_end>=period_start),status text not null default'generated' check(status in('generated','reviewed','superseded')),
 payload jsonb not null check(jsonb_typeof(payload)='object'),reconciliation jsonb not null check(jsonb_typeof(reconciliation)='object'),
 generated_by uuid references auth.users(id),generated_at timestamptz not null default now(),reviewed_by uuid references auth.users(id),reviewed_at timestamptz,review_note text,
 unique(report_type,period_start,period_end)
);
create index management_report_snapshots_period_idx on public.management_report_snapshots(report_type,period_end desc);
alter table public.management_report_snapshots enable row level security;
revoke all on public.management_report_snapshots from public,anon,authenticated;
grant all on public.management_report_snapshots to service_role;

create function private.generate_management_report_snapshot(p_type text,p_start date,p_end date,p_actor uuid default null)
returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare v_id uuid;v_payload jsonb;v_recon jsonb;v_sales numeric;v_customer numeric;v_refunds numeric;v_supplier numeric;v_cost numeric;
begin
 if p_type not in('operational','finance','corporate','management')or p_start is null or p_end is null or p_end<p_start or p_end-p_start>366 then raise exception'Invalid report period';end if;
 select coalesce(sum(coalesce(selling_price,amount,0)),0),coalesce(sum(coalesce(supplier_cost,0)),0)into v_sales,v_cost from public.bookings where archived_at is null and created_at::date between p_start and p_end;
 select coalesce(sum(case when payment_direction='incoming'and status in('received','completed','paid','verified')then amount else 0 end),0)into v_customer from public.payments where created_at::date between p_start and p_end;
 select coalesce(sum(case when status in('approved','paid','completed')then amount else 0 end),0)into v_refunds from public.refunds where created_at::date between p_start and p_end;
 select coalesce(sum(amount_payable),0)into v_supplier from public.supplier_payments where created_at::date between p_start and p_end;
 v_recon:=jsonb_build_object('booking_sales',v_sales,'customer_money_received',v_customer,'approved_or_paid_refunds',v_refunds,'supplier_payables',v_supplier,'booking_supplier_cost',v_cost,'customer_receipt_variance',v_sales-v_customer-v_refunds,'supplier_cost_variance',v_cost-v_supplier,'currency_basis','native recorded values; multi-currency review required when currencies differ');
 if p_type='operational'then v_payload:=jsonb_build_object('enquiries_created',(select count(*)from public.enquiries where created_at::date between p_start and p_end),'bookings_created',(select count(*)from public.bookings where archived_at is null and created_at::date between p_start and p_end),'open_overdue_tasks',(select count(*)from public.tasks_reminders where status<>'done'and due_at<now()),'open_exceptions',(select count(*)from public.operational_exceptions where status not in('resolved','closed')),'critical_open_exceptions',(select count(*)from public.operational_exceptions where status not in('resolved','closed')and severity='critical'));
 elsif p_type='finance'then v_payload:=jsonb_build_object('sales',v_sales,'supplier_cost',v_cost,'gross_margin',v_sales-v_cost,'customer_money_received',v_customer,'refunds',v_refunds,'supplier_payables',v_supplier,'customer_payments_by_status',(select coalesce(jsonb_object_agg(status,total),'{}')from(select status,sum(amount)total from public.payments where created_at::date between p_start and p_end group by status)x),'supplier_payments_by_status',(select coalesce(jsonb_object_agg(status,total),'{}')from(select status,sum(amount_payable)total from public.supplier_payments where created_at::date between p_start and p_end group by status)x));
 elsif p_type='corporate'then v_payload:=jsonb_build_object('active_accounts',(select count(*)from public.corporate_accounts where archived_at is null and status='active'),'corporate_bookings',(select count(*)from public.bookings where corporate_account_id is not null and archived_at is null and created_at::date between p_start and p_end),'corporate_booking_value',(select coalesce(sum(coalesce(selling_price,amount,0)),0)from public.bookings where corporate_account_id is not null and archived_at is null and created_at::date between p_start and p_end),'company_rows',(select coalesce(jsonb_agg(to_jsonb(x)order by x.company_name),'[]')from(select a.id,a.company_name,count(b.id)booking_count,coalesce(sum(coalesce(b.selling_price,b.amount,0)),0)booking_value from public.corporate_accounts a left join public.bookings b on b.corporate_account_id=a.id and b.archived_at is null and b.created_at::date between p_start and p_end where a.archived_at is null group by a.id,a.company_name)x));
 else v_payload:=jsonb_build_object('sales',v_sales,'gross_margin',v_sales-v_cost,'margin_percent',case when v_sales=0 then 0 else round((v_sales-v_cost)*100/v_sales,2)end,'enquiries',(select count(*)from public.enquiries where created_at::date between p_start and p_end),'bookings',(select count(*)from public.bookings where archived_at is null and created_at::date between p_start and p_end),'conversion_percent',(select case when count(*)=0 then 0 else round(count(*)filter(where booking_confirmed_at is not null)*100.0/count(*),2)end from public.enquiries where created_at::date between p_start and p_end),'open_workload',(select count(*)from public.tasks_reminders where status<>'done'),'open_exceptions',(select count(*)from public.operational_exceptions where status not in('resolved','closed')));
 end if;
 insert into public.management_report_snapshots(report_type,period_start,period_end,payload,reconciliation,generated_by)values(p_type,p_start,p_end,v_payload,v_recon,p_actor)on conflict(report_type,period_start,period_end)do update set payload=excluded.payload,reconciliation=excluded.reconciliation,generated_by=excluded.generated_by,generated_at=now(),status='generated',reviewed_by=null,reviewed_at=null,review_note=null returning id into v_id;
 insert into public.audit_events(actor_user_id,event_type,entity_type,entity_id,metadata)values(p_actor,'management_report.generated','management_report_snapshot',v_id,jsonb_build_object('report_type',p_type,'period_start',p_start,'period_end',p_end));return v_id;
end$$;
revoke all on function private.generate_management_report_snapshot(text,date,date,uuid)from public,anon,authenticated;

create function private.generate_scheduled_management_reports()returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare v_date date:=current_date-1;v_ids uuid[]:='{}';begin v_ids:=array_append(v_ids,private.generate_management_report_snapshot('operational',v_date,v_date,null));v_ids:=array_append(v_ids,private.generate_management_report_snapshot('finance',date_trunc('month',v_date)::date,v_date,null));v_ids:=array_append(v_ids,private.generate_management_report_snapshot('management',date_trunc('week',v_date)::date,v_date,null));if extract(day from current_date)=1 then v_ids:=array_append(v_ids,private.generate_management_report_snapshot('corporate',(date_trunc('month',current_date)-interval'1 month')::date,(date_trunc('month',current_date)-interval'1 day')::date,null));end if;return jsonb_build_object('snapshot_ids',v_ids,'generated_at',now());end$$;
revoke all on function private.generate_scheduled_management_reports()from public,anon,authenticated;

create function public.generate_management_report(p_type text,p_start date,p_end date)returns uuid language plpgsql security definer set search_path=public,pg_temp as $$declare v_actor uuid:=auth.uid();begin if v_actor is null or not public.has_staff_permission('view_reports')then raise exception'Report permission required';end if;return private.generate_management_report_snapshot(lower(btrim(p_type)),p_start,p_end,v_actor);end$$;
create function public.list_management_reports(p_type text default null,p_limit integer default 100)returns jsonb language sql stable security definer set search_path=public,pg_temp as $$select case when public.has_staff_permission('view_reports')then coalesce(jsonb_agg(to_jsonb(x)order by x.period_end desc,x.generated_at desc),'[]')else'[]'::jsonb end from(select*from public.management_report_snapshots where p_type is null or report_type=p_type order by period_end desc,generated_at desc limit least(greatest(coalesce(p_limit,100),1),300))x$$;
create function public.review_management_report(p_id uuid,p_note text)returns void language plpgsql security definer set search_path=public,pg_temp as $$declare v_actor uuid:=auth.uid();begin if v_actor is null or not public.is_admin()then raise exception'Owner/admin access required';end if;if char_length(btrim(coalesce(p_note,'')))<10 then raise exception'Review note is required';end if;update public.management_report_snapshots set status='reviewed',reviewed_by=v_actor,reviewed_at=now(),review_note=btrim(p_note)where id=p_id;if not found then raise exception'Report not found';end if;insert into public.audit_events(actor_user_id,event_type,entity_type,entity_id,metadata)values(v_actor,'management_report.reviewed','management_report_snapshot',p_id,jsonb_build_object('note',btrim(p_note)));end$$;
revoke execute on function public.generate_management_report(text,date,date),public.list_management_reports(text,integer),public.review_management_report(uuid,text)from public,anon;
grant execute on function public.generate_management_report(text,date,date),public.list_management_reports(text,integer),public.review_management_report(uuid,text)to authenticated,service_role;
do $$declare v_job bigint;begin if exists(select 1 from pg_extension where extname='pg_cron')then select jobid into v_job from cron.job where jobname='kridiya-management-reports'limit 1;if v_job is not null then perform cron.unschedule(v_job);end if;perform cron.schedule('kridiya-management-reports','15 2 * * *',$job$select private.generate_scheduled_management_reports()$job$);end if;end$$;
commit;
