create table public.travel_disruptions(
 id uuid primary key default gen_random_uuid(),source_type text not null check(source_type in('airline','hotel','visa','transfer','weather','security','supplier','other')),severity text not null check(severity in('low','medium','high','critical')),status text not null default'assessing' check(status in('assessing','active','monitoring','resolved','closed')),title text not null check(char_length(btrim(title))between 3 and 180),summary text not null check(char_length(btrim(summary))between 10 and 4000),route_filter text,supplier_filter text,impact_start timestamptz,impact_end timestamptz,owner_user_id uuid references auth.users(id)on delete set null,next_update_at timestamptz,operational_exception_id uuid references public.operational_exceptions(id)on delete set null,created_by uuid not null references auth.users(id)on delete restrict,resolved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.travel_disruption_bookings(
 disruption_id uuid not null references public.travel_disruptions(id)on delete cascade,booking_id uuid not null references public.bookings(id)on delete restrict,impact_status text not null default'affected' check(impact_status in('potentially_affected','affected','contacted','rebooked','refunded','unaffected','resolved')),action_required text,customer_acknowledged_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(disruption_id,booking_id)
);
create table public.travel_disruption_updates(
 id uuid primary key default gen_random_uuid(),disruption_id uuid not null references public.travel_disruptions(id)on delete cascade,update_type text not null check(update_type in('initial','progress','option','resolution')),audience text not null default'affected_customers' check(audience in('internal','affected_customers')),message text not null check(char_length(btrim(message))between 10 and 4000),status text not null default'draft' check(status in('draft','published','withdrawn')),next_update_at timestamptz,created_by uuid not null references auth.users(id)on delete restrict,published_by uuid references auth.users(id)on delete set null,published_at timestamptz,created_at timestamptz not null default now()
);
create index travel_disruptions_queue_idx on public.travel_disruptions(status,severity,next_update_at);
create index travel_disruption_bookings_booking_idx on public.travel_disruption_bookings(booking_id,disruption_id);
create index travel_disruption_updates_timeline_idx on public.travel_disruption_updates(disruption_id,created_at desc);
alter table public.travel_disruptions enable row level security;alter table public.travel_disruption_bookings enable row level security;alter table public.travel_disruption_updates enable row level security;
revoke all on public.travel_disruptions,public.travel_disruption_bookings,public.travel_disruption_updates from public,anon,authenticated;
grant all on public.travel_disruptions,public.travel_disruption_bookings,public.travel_disruption_updates to service_role;

create function public.preview_disruption_affected_bookings(p_service_type text default null,p_route text default null,p_supplier text default null,p_travel_from date default null,p_travel_to date default null,p_limit integer default 300)
returns table(id uuid,booking_reference text,title text,service_type text,route_or_destination text,travel_start date,travel_end date,supplier_name text,booking_kind text,customer_name text,company_name text)
language sql stable security definer set search_path=public,pg_temp as $$
 select b.id,b.booking_reference,b.title,b.service_type::text,b.route_or_destination,b.travel_start,b.travel_end,b.supplier_name,b.booking_kind,c.full_name,a.company_name
 from public.bookings b left join public.customers c on c.id=b.customer_id left join public.corporate_accounts a on a.id=b.corporate_account_id
 where public.is_staff()and b.archived_at is null and b.status::text not in('cancelled','refunded')
 and(p_service_type is null or p_service_type='' or b.service_type::text=lower(p_service_type))
 and(p_route is null or b.route_or_destination ilike'%'||btrim(p_route)||'%')
 and(p_supplier is null or b.supplier_name ilike'%'||btrim(p_supplier)||'%')
 and(p_travel_from is null or coalesce(b.travel_end,b.travel_start)>=p_travel_from)
 and(p_travel_to is null or coalesce(b.travel_start,b.travel_end)<=p_travel_to)
 order by b.travel_start nulls last,b.created_at desc limit least(greatest(coalesce(p_limit,300),1),500)
$$;

create function public.create_travel_disruption(p_source_type text,p_severity text,p_title text,p_summary text,p_route_filter text,p_supplier_filter text,p_impact_start timestamptz,p_impact_end timestamptz,p_owner_user_id uuid,p_booking_ids uuid[])
returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare v_actor uuid:=auth.uid();v_id uuid;v_exception uuid;v_task uuid;v_count integer;v_source text:=lower(btrim(coalesce(p_source_type,'')));v_severity text:=lower(btrim(coalesce(p_severity,'')));
begin
 if v_actor is null or not public.is_staff()then raise exception'Staff access required';end if;
 if v_source not in('airline','hotel','visa','transfer','weather','security','supplier','other')then raise exception'Invalid disruption source';end if;
 if v_severity not in('low','medium','high','critical')then raise exception'Invalid severity';end if;
 if char_length(btrim(coalesce(p_title,'')))not between 3 and 180 or char_length(btrim(coalesce(p_summary,'')))not between 10 and 4000 then raise exception'Title or summary is invalid';end if;
 if p_impact_end is not null and p_impact_start is not null and p_impact_end<p_impact_start then raise exception'Impact end must follow impact start';end if;
 if p_owner_user_id is not null and not exists(select 1 from public.staff_profiles where user_id=p_owner_user_id and active)then raise exception'Owner must be active staff';end if;
 select count(distinct x)into v_count from unnest(coalesce(p_booking_ids,'{}'))x;
 if v_count<1 or v_count>200 then raise exception'Select 1 to 200 affected bookings';end if;
 if(select count(*)from public.bookings where id=any(p_booking_ids)and archived_at is null)<>v_count then raise exception'One or more bookings are invalid';end if;
 insert into public.operational_exceptions(category,severity,urgency,title,description,entity_type,owner_user_id,response_due_at,resolution_due_at,evidence,created_by)
 values('travel_disruption',v_severity,case when v_severity='critical'then'immediate'when v_severity='high'then'urgent'else'normal'end,btrim(p_title),btrim(p_summary),'system',p_owner_user_id,now()+case when v_severity='critical'then interval'15 minutes'when v_severity='high'then interval'1 hour'else interval'4 hours'end,now()+case when v_severity in('critical','high')then interval'8 hours'else interval'1 day'end,jsonb_build_array(jsonb_build_object('affected_booking_count',v_count,'source_type',v_source)),v_actor)returning id into v_exception;
 insert into public.travel_disruptions(source_type,severity,title,summary,route_filter,supplier_filter,impact_start,impact_end,owner_user_id,next_update_at,operational_exception_id,created_by)
 values(v_source,v_severity,btrim(p_title),btrim(p_summary),nullif(btrim(coalesce(p_route_filter,'')),''),nullif(btrim(coalesce(p_supplier_filter,'')),''),p_impact_start,p_impact_end,p_owner_user_id,now()+case when v_severity='critical'then interval'30 minutes'else interval'2 hours'end,v_exception,v_actor)returning id into v_id;
 insert into public.travel_disruption_bookings(disruption_id,booking_id)select v_id,x from unnest(p_booking_ids)x group by x;
 insert into public.tasks_reminders(title,task_type,entity_type,entity_id,due_at,priority,assigned_to,notes,created_by,automation_key)values('Disruption response: '||left(btrim(p_title),150),'follow_up','travel_disruption',v_id,now()+case when v_severity='critical'then interval'15 minutes'else interval'1 hour'end,case when v_severity in('critical','high')then'urgent'else'high'end,p_owner_user_id,'Assess affected bookings, prepare a reviewed update and publish it through the Disruption Centre.',v_actor,'travel-disruption:'||v_id)returning id into v_task;
 update public.operational_exceptions set entity_type='system',entity_id=v_id,task_id=v_task where id=v_exception;
 insert into public.audit_events(actor_user_id,event_type,entity_type,entity_id,metadata)values(v_actor,'travel_disruption.created','travel_disruption',v_id,jsonb_build_object('source_type',v_source,'severity',v_severity,'affected_booking_count',v_count,'operational_exception_id',v_exception,'task_id',v_task));return v_id;
end$$;

create function public.save_travel_disruption_update(p_disruption_id uuid,p_update_type text,p_audience text,p_message text,p_next_update_at timestamptz,p_publish boolean default false)
returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare v_actor uuid:=auth.uid();v_id uuid;v_type text:=lower(btrim(coalesce(p_update_type,'')));v_audience text:=lower(btrim(coalesce(p_audience,'')));v_disruption public.travel_disruptions%rowtype;
begin
 if v_actor is null or not public.is_staff()then raise exception'Staff access required';end if;if v_type not in('initial','progress','option','resolution')then raise exception'Invalid update type';end if;if v_audience not in('internal','affected_customers')then raise exception'Invalid audience';end if;if char_length(btrim(coalesce(p_message,'')))not between 10 and 4000 then raise exception'Update must be 10 to 4000 characters';end if;
 select*into v_disruption from public.travel_disruptions where id=p_disruption_id for update;if not found then raise exception'Disruption not found';end if;
 insert into public.travel_disruption_updates(disruption_id,update_type,audience,message,status,next_update_at,created_by,published_by,published_at)values(p_disruption_id,v_type,v_audience,btrim(p_message),case when p_publish then'published'else'draft'end,p_next_update_at,v_actor,case when p_publish then v_actor end,case when p_publish then now()end)returning id into v_id;
 if p_publish and v_audience='affected_customers'then
  insert into public.customer_communication_history(user_id,channel,category,subject,delivery_status,entity_type,entity_id,dedupe_key)
  select distinct coalesce(b.user_id,c.auth_user_id),'portal','booking',left(v_disruption.title,180),'available','travel_disruption',p_disruption_id,'travel-disruption-update:'||v_id||':'||coalesce(b.user_id,c.auth_user_id)::text from public.travel_disruption_bookings db join public.bookings b on b.id=db.booking_id left join public.customers c on c.id=b.customer_id where db.disruption_id=p_disruption_id and coalesce(b.user_id,c.auth_user_id)is not null on conflict(dedupe_key)where dedupe_key is not null do nothing;
  update public.travel_disruption_bookings set impact_status=case when impact_status in('potentially_affected','affected')then'contacted'else impact_status end,updated_at=now()where disruption_id=p_disruption_id;
 end if;
 update public.travel_disruptions set status=case when p_publish and status='assessing'then'active'else status end,next_update_at=p_next_update_at,updated_at=now()where id=p_disruption_id;
 update public.operational_exceptions set external_update=case when p_publish and v_audience='affected_customers'then btrim(p_message)else external_update end,updated_at=now()where id=v_disruption.operational_exception_id;
 insert into public.audit_events(actor_user_id,event_type,entity_type,entity_id,metadata)values(v_actor,case when p_publish then'travel_disruption.update_published'else'travel_disruption.update_drafted'end,'travel_disruption',p_disruption_id,jsonb_build_object('update_id',v_id,'update_type',v_type,'audience',v_audience,'next_update_at',p_next_update_at));return v_id;
end$$;

create function public.list_travel_disruptions(p_status text default null,p_limit integer default 200)returns jsonb language sql stable security definer set search_path=public,pg_temp as $$
 select coalesce(jsonb_agg(to_jsonb(x)order by x.created_at desc),'[]')from(select d.*,(select count(*)from public.travel_disruption_bookings b where b.disruption_id=d.id)affected_count,(select coalesce(jsonb_agg(jsonb_build_object('id',u.id,'update_type',u.update_type,'audience',u.audience,'message',u.message,'status',u.status,'next_update_at',u.next_update_at,'published_at',u.published_at,'created_at',u.created_at)order by u.created_at desc),'[]')from public.travel_disruption_updates u where u.disruption_id=d.id)updates from public.travel_disruptions d where public.is_staff()and(p_status is null or d.status=p_status)order by case d.severity when'critical'then 0 when'high'then 1 else 2 end,d.created_at desc limit least(greatest(coalesce(p_limit,200),1),500))x
$$;
create function public.list_my_travel_disruptions(p_limit integer default 100)returns jsonb language sql stable security definer set search_path=public,pg_temp as $$select coalesce(jsonb_agg(x.payload order by x.created_at desc),'[]')from(select d.created_at,jsonb_build_object('id',d.id,'source_type',d.source_type,'severity',d.severity,'status',d.status,'title',d.title,'summary',d.summary,'impact_start',d.impact_start,'impact_end',d.impact_end,'next_update_at',d.next_update_at,'booking_reference',b.booking_reference,'impact_status',db.impact_status,'updates',(select coalesce(jsonb_agg(jsonb_build_object('update_type',u.update_type,'message',u.message,'next_update_at',u.next_update_at,'published_at',u.published_at)order by u.created_at desc),'[]')from public.travel_disruption_updates u where u.disruption_id=d.id and u.status='published'and u.audience='affected_customers'))payload from public.travel_disruptions d join public.travel_disruption_bookings db on db.disruption_id=d.id join public.bookings b on b.id=db.booking_id left join public.customers c on c.id=b.customer_id where auth.uid()is not null and coalesce(b.user_id,c.auth_user_id)=auth.uid()order by d.created_at desc limit least(greatest(coalesce(p_limit,100),1),200))x$$;
create function public.list_my_corporate_travel_disruptions(p_corporate_account_id uuid,p_limit integer default 100)returns jsonb language sql stable security definer set search_path=public,pg_temp as $$select coalesce(jsonb_agg(x.payload order by x.created_at desc),'[]')from(select d.created_at,jsonb_build_object('id',d.id,'source_type',d.source_type,'severity',d.severity,'status',d.status,'title',d.title,'summary',d.summary,'impact_start',d.impact_start,'impact_end',d.impact_end,'next_update_at',d.next_update_at,'booking_reference',b.booking_reference,'impact_status',db.impact_status,'updates',(select coalesce(jsonb_agg(jsonb_build_object('update_type',u.update_type,'message',u.message,'next_update_at',u.next_update_at,'published_at',u.published_at)order by u.created_at desc),'[]')from public.travel_disruption_updates u where u.disruption_id=d.id and u.status='published'and u.audience='affected_customers'))payload from public.travel_disruptions d join public.travel_disruption_bookings db on db.disruption_id=d.id join public.bookings b on b.id=db.booking_id where b.corporate_account_id=p_corporate_account_id and exists(select 1 from public.corporate_portal_members m where m.user_id=auth.uid()and m.corporate_account_id=b.corporate_account_id and m.status='active')order by d.created_at desc limit least(greatest(coalesce(p_limit,100),1),200))x$$;
revoke execute on function public.preview_disruption_affected_bookings(text,text,text,date,date,integer),public.create_travel_disruption(text,text,text,text,text,text,timestamptz,timestamptz,uuid,uuid[]),public.save_travel_disruption_update(uuid,text,text,text,timestamptz,boolean),public.list_travel_disruptions(text,integer),public.list_my_travel_disruptions(integer),public.list_my_corporate_travel_disruptions(uuid,integer)from public,anon;
grant execute on function public.preview_disruption_affected_bookings(text,text,text,date,date,integer),public.create_travel_disruption(text,text,text,text,text,text,timestamptz,timestamptz,uuid,uuid[]),public.save_travel_disruption_update(uuid,text,text,text,timestamptz,boolean),public.list_travel_disruptions(text,integer),public.list_my_travel_disruptions(integer),public.list_my_corporate_travel_disruptions(uuid,integer)to authenticated,service_role;
