create table public.controlled_incidents(
 id uuid primary key default gen_random_uuid(),exception_id uuid not null unique references public.operational_exceptions(id)on delete restrict,incident_type text not null check(incident_type in('security','privacy','payment','document','cross_company')),classification text not null check(classification in('suspected','confirmed','false_positive')),status text not null default'triage'check(status in('triage','contained','investigating','notification_assessment','recovering','resolved','closed')),detection_source text not null check(char_length(btrim(detection_source))between 3 and 300),restricted_facts text not null check(char_length(btrim(restricted_facts))between 10 and 5000),affected_subject_count integer check(affected_subject_count between 0 and 1000000),personal_data_involved boolean not null default false,financial_data_involved boolean not null default false,cross_company_exposure boolean not null default false,access_contained boolean not null default false,credentials_rotated boolean not null default false,payment_held boolean not null default false,document_revoked boolean not null default false,company_scope_verified boolean not null default false,evidence_preserved boolean not null default false,notification_assessment_due_at timestamptz not null,notification_decision text check(notification_decision in('not_assessed','not_required','customer_required','regulator_required','customer_and_regulator_required')),notification_rationale text,customer_notified_at timestamptz,regulator_notified_at timestamptz,legal_reviewed_at timestamptz,legal_reviewed_by uuid references auth.users(id)on delete set null,investigation_owner uuid not null references auth.users(id)on delete restrict,resolution_summary text,root_cause text,preventive_action text,created_by uuid not null references auth.users(id)on delete restrict,resolved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create index controlled_incidents_queue_idx on public.controlled_incidents(status,incident_type,notification_assessment_due_at);
alter table public.controlled_incidents enable row level security;revoke all on public.controlled_incidents from public,anon,authenticated;grant all on public.controlled_incidents to service_role;
comment on table public.controlled_incidents is'Restricted incident investigation controls. Never store credentials, raw payment data, passport images or unnecessary personal data in restricted_facts.';

create function public.controlled_incident_playbook(p_incident_type text)returns jsonb language sql immutable security invoker set search_path=public,pg_temp as $$
 select case lower(btrim(coalesce(p_incident_type,'')))
 when'security'then jsonb_build_object('required',jsonb_build_array('access_contained','credentials_rotated','evidence_preserved'),'first_actions',jsonb_build_array('Restrict affected access','Preserve logs and timestamps','Rotate exposed credentials','Assess customer and regulator notification'))
 when'privacy'then jsonb_build_object('required',jsonb_build_array('access_contained','evidence_preserved'),'first_actions',jsonb_build_array('Stop further disclosure','Preserve minimum necessary evidence','Identify affected data subjects','Complete notification assessment'))
 when'payment'then jsonb_build_object('required',jsonb_build_array('payment_held','evidence_preserved'),'first_actions',jsonb_build_array('Hold unsettled movement','Preserve provider references','Verify maker-checker trail','Reconcile before release'))
 when'document'then jsonb_build_object('required',jsonb_build_array('document_revoked','evidence_preserved'),'first_actions',jsonb_build_array('Revoke or supersede incorrect document','Preserve issuance trail','Identify recipients','Issue corrected version through controlled release'))
 when'cross_company'then jsonb_build_object('required',jsonb_build_array('access_contained','company_scope_verified','evidence_preserved'),'first_actions',jsonb_build_array('Stop cross-company access','Verify both company scopes','Preserve response payload evidence','Complete notification assessment'))
 else jsonb_build_object('required','[]'::jsonb,'first_actions','[]'::jsonb)end
$$;

create function public.report_controlled_incident(p_incident_type text,p_severity text,p_title text,p_detection_source text,p_restricted_facts text,p_affected_subject_count integer default null,p_personal_data_involved boolean default false,p_financial_data_involved boolean default false,p_cross_company_exposure boolean default false,p_entity_type text default'system',p_entity_id uuid default null)
returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare v_actor uuid:=auth.uid();v_owner uuid;v_exception uuid;v_task uuid;v_id uuid;v_type text:=lower(btrim(coalesce(p_incident_type,'')));v_severity text:=lower(btrim(coalesce(p_severity,'')));v_due timestamptz;
begin
 if v_actor is null or not public.is_staff()then raise exception'Staff access required';end if;if v_type not in('security','privacy','payment','document','cross_company')then raise exception'Invalid incident type';end if;if v_severity not in('low','medium','high','critical')then raise exception'Invalid severity';end if;if char_length(btrim(coalesce(p_title,'')))not between 3 and 180 or char_length(btrim(coalesce(p_detection_source,'')))not between 3 and 300 or char_length(btrim(coalesce(p_restricted_facts,'')))not between 10 and 5000 then raise exception'Incident details are incomplete';end if;if p_affected_subject_count is not null and p_affected_subject_count not between 0 and 1000000 then raise exception'Invalid affected subject count';end if;
 select sr.user_id into v_owner from public.staff_roles sr join public.staff_profiles sp on sp.user_id=sr.user_id and sp.active where sr.role::text='owner'order by sr.created_at limit 1;if v_owner is null then raise exception'No active owner is available';end if;v_due:=now()+case when v_severity='critical'or v_type in('privacy','cross_company')then interval'1 hour'when v_severity='high'then interval'4 hours'else interval'1 day'end;
 insert into public.operational_exceptions(category,severity,urgency,title,description,entity_type,entity_id,owner_user_id,response_due_at,resolution_due_at,evidence,created_by)values(case when v_type='cross_company'then'cross_company'else v_type end,v_severity,case when v_severity='critical'then'immediate'when v_severity='high'then'urgent'else'normal'end,btrim(p_title),'Restricted incident reported. Sensitive investigation facts are available only in the Incident Control Centre.',p_entity_type,p_entity_id,v_owner,now()+case when v_severity='critical'then interval'15 minutes'else interval'1 hour'end,now()+case when v_severity in('critical','high')then interval'8 hours'else interval'1 day'end,jsonb_build_array(jsonb_build_object('incident_type',v_type,'affected_subject_count',p_affected_subject_count)),v_actor)returning id into v_exception;
 insert into public.controlled_incidents(exception_id,incident_type,classification,detection_source,restricted_facts,affected_subject_count,personal_data_involved,financial_data_involved,cross_company_exposure,notification_assessment_due_at,notification_decision,investigation_owner,created_by)values(v_exception,v_type,'suspected',btrim(p_detection_source),btrim(p_restricted_facts),p_affected_subject_count,coalesce(p_personal_data_involved,false),coalesce(p_financial_data_involved,false),coalesce(p_cross_company_exposure,false),v_due,'not_assessed',v_owner,v_actor)returning id into v_id;
 insert into public.tasks_reminders(title,task_type,entity_type,entity_id,due_at,priority,assigned_to,notes,created_by,automation_key)values('Restricted incident: '||left(btrim(p_title),155),'follow_up','controlled_incident',v_id,least(v_due,now()+interval'1 hour'),'urgent',v_owner,'Open the restricted Incident Control Centre. Do not copy sensitive facts into ordinary task notes.',v_actor,'controlled-incident:'||v_id)returning id into v_task;update public.operational_exceptions set task_id=v_task where id=v_exception;
 insert into public.audit_events(actor_user_id,event_type,entity_type,entity_id,metadata)values(v_actor,'controlled_incident.reported','controlled_incident',v_id,jsonb_build_object('incident_type',v_type,'severity',v_severity,'exception_id',v_exception,'task_id',v_task,'notification_assessment_due_at',v_due));return v_id;
end$$;

create function public.list_controlled_incidents(p_status text default null,p_limit integer default 200)returns jsonb language sql stable security definer set search_path=public,pg_temp as $$select case when public.is_admin()then coalesce(jsonb_agg(to_jsonb(x)order by x.created_at desc),'[]')else'[]'::jsonb end from(select i.*,e.title,e.severity,e.entity_type,e.entity_id,e.response_due_at,e.resolution_due_at,e.task_id,public.controlled_incident_playbook(i.incident_type)playbook from public.controlled_incidents i join public.operational_exceptions e on e.id=i.exception_id where(p_status is null or i.status=p_status)order by case e.severity when'critical'then 0 when'high'then 1 else 2 end,i.notification_assessment_due_at,i.created_at desc limit least(greatest(coalesce(p_limit,200),1),500))x$$;

create function public.update_controlled_incident(p_incident_id uuid,p_status text,p_classification text,p_access_contained boolean,p_credentials_rotated boolean,p_payment_held boolean,p_document_revoked boolean,p_company_scope_verified boolean,p_evidence_preserved boolean,p_notification_decision text,p_notification_rationale text,p_customer_notified_at timestamptz,p_regulator_notified_at timestamptz,p_resolution_summary text,p_root_cause text,p_preventive_action text)
returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare v_actor uuid:=auth.uid();v_old public.controlled_incidents%rowtype;v_status text:=lower(btrim(coalesce(p_status,'')));v_class text:=lower(btrim(coalesce(p_classification,'')));v_decision text:=lower(btrim(coalesce(p_notification_decision,'')));v_close boolean;
begin
 if v_actor is null or not public.is_admin()then raise exception'Owner/admin access required';end if;if v_status not in('triage','contained','investigating','notification_assessment','recovering','resolved','closed')or v_class not in('suspected','confirmed','false_positive')or v_decision not in('not_assessed','not_required','customer_required','regulator_required','customer_and_regulator_required')then raise exception'Invalid incident update';end if;select*into v_old from public.controlled_incidents where id=p_incident_id for update;if not found then raise exception'Incident not found';end if;v_close:=v_status in('resolved','closed');
 if v_close and v_decision='not_assessed'then raise exception'Notification decision is required before closure';end if;if v_close and char_length(btrim(coalesce(p_notification_rationale,'')))<10 then raise exception'Notification rationale is required before closure';end if;if v_close and(char_length(btrim(coalesce(p_resolution_summary,'')))<10 or char_length(btrim(coalesce(p_root_cause,'')))<10 or char_length(btrim(coalesce(p_preventive_action,'')))<10)then raise exception'Resolution, root cause and preventive action are required';end if;
 if v_close and not coalesce(p_evidence_preserved,false)then raise exception'Evidence preservation must be confirmed';end if;if v_close and v_old.incident_type in('security','privacy','cross_company')and not coalesce(p_access_contained,false)then raise exception'Access containment must be confirmed';end if;if v_close and v_old.incident_type='security'and not coalesce(p_credentials_rotated,false)then raise exception'Credential rotation must be confirmed';end if;if v_close and v_old.incident_type='payment'and not coalesce(p_payment_held,false)then raise exception'Payment hold/reconciliation must be confirmed';end if;if v_close and v_old.incident_type='document'and not coalesce(p_document_revoked,false)then raise exception'Document revocation or supersession must be confirmed';end if;if v_close and v_old.incident_type='cross_company'and not coalesce(p_company_scope_verified,false)then raise exception'Company scope verification must be confirmed';end if;if v_close and v_decision in('customer_required','customer_and_regulator_required')and p_customer_notified_at is null then raise exception'Customer notification timestamp is required';end if;if v_close and v_decision in('regulator_required','customer_and_regulator_required')and p_regulator_notified_at is null then raise exception'Regulator notification timestamp is required';end if;
 update public.controlled_incidents set status=v_status,classification=v_class,access_contained=coalesce(p_access_contained,false),credentials_rotated=coalesce(p_credentials_rotated,false),payment_held=coalesce(p_payment_held,false),document_revoked=coalesce(p_document_revoked,false),company_scope_verified=coalesce(p_company_scope_verified,false),evidence_preserved=coalesce(p_evidence_preserved,false),notification_decision=v_decision,notification_rationale=nullif(btrim(coalesce(p_notification_rationale,'')),''),customer_notified_at=p_customer_notified_at,regulator_notified_at=p_regulator_notified_at,legal_reviewed_at=case when v_decision<>'not_assessed'then now()else legal_reviewed_at end,legal_reviewed_by=case when v_decision<>'not_assessed'then v_actor else legal_reviewed_by end,resolution_summary=nullif(btrim(coalesce(p_resolution_summary,'')),''),root_cause=nullif(btrim(coalesce(p_root_cause,'')),''),preventive_action=nullif(btrim(coalesce(p_preventive_action,'')),''),resolved_at=case when v_close then coalesce(resolved_at,now())else null end,updated_at=now()where id=p_incident_id;
 update public.operational_exceptions set status=case when v_close then'resolved'when v_status='contained'then'contained'when v_status in('recovering','notification_assessment')then'recovering'else'open'end,containment=case when coalesce(p_access_contained,false)or coalesce(p_payment_held,false)or coalesce(p_document_revoked,false)then'Category-specific containment checklist confirmed in restricted incident record.'else containment end,resolution=case when v_close then btrim(p_resolution_summary)else resolution end,root_cause=case when v_close then btrim(p_root_cause)else root_cause end,preventive_action=case when v_close then btrim(p_preventive_action)else preventive_action end,resolved_at=case when v_close then coalesce(resolved_at,now())else null end,updated_at=now()where id=v_old.exception_id;
 update public.tasks_reminders set status=case when v_close then'done'else status end,completed_at=case when v_close then coalesce(completed_at,now())else completed_at end where id=(select task_id from public.operational_exceptions where id=v_old.exception_id);
 insert into public.audit_events(actor_user_id,event_type,entity_type,entity_id,metadata)values(v_actor,'controlled_incident.updated','controlled_incident',p_incident_id,jsonb_build_object('from_status',v_old.status,'to_status',v_status,'classification',v_class,'notification_decision',v_decision,'closed',v_close));
end$$;
revoke execute on function public.controlled_incident_playbook(text),public.report_controlled_incident(text,text,text,text,text,integer,boolean,boolean,boolean,text,uuid),public.list_controlled_incidents(text,integer),public.update_controlled_incident(uuid,text,text,boolean,boolean,boolean,boolean,boolean,boolean,text,text,timestamptz,timestamptz,text,text,text)from public,anon;
grant execute on function public.controlled_incident_playbook(text),public.report_controlled_incident(text,text,text,text,text,integer,boolean,boolean,boolean,text,uuid),public.list_controlled_incidents(text,integer),public.update_controlled_incident(uuid,text,text,boolean,boolean,boolean,boolean,boolean,boolean,text,text,timestamptz,timestamptz,text,text,text)to authenticated,service_role;
