create table public.operational_exceptions(id uuid primary key default gen_random_uuid(),category text not null check(category in('travel_disruption','supplier','payment','document','security','privacy','integration','data_quality','cross_company','deadline','other')),severity text not null check(severity in('low','medium','high','critical')),urgency text not null check(urgency in('normal','urgent','immediate')),status text not null default'open'check(status in('open','contained','recovering','waiting_external','resolved','closed')),title text not null check(char_length(btrim(title))between 3 and 180),description text not null check(char_length(btrim(description))between 10 and 5000),entity_type text not null check(entity_type in('booking','enquiry','payment','document','supplier','corporate_desk_case','customer','integration','system','other')),entity_id uuid,owner_user_id uuid references auth.users(id)on delete set null,response_due_at timestamptz not null,resolution_due_at timestamptz not null,evidence jsonb not null default'[]',external_update text,containment text,recovery_action text,resolution text,root_cause text,preventive_action text,escalation_level integer not null default 0 check(escalation_level between 0 and 5),escalated_at timestamptz,contained_at timestamptz,resolved_at timestamptz,task_id uuid references public.tasks_reminders(id)on delete set null,created_by uuid not null references auth.users(id)on delete restrict,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index operational_exceptions_open_entity_uidx on public.operational_exceptions(entity_type,entity_id,category)where entity_id is not null and status not in('resolved','closed');
create index operational_exceptions_queue_idx on public.operational_exceptions(status,severity,response_due_at);
alter table public.operational_exceptions enable row level security;revoke all on public.operational_exceptions from anon,authenticated;grant all on public.operational_exceptions to service_role;

create function public.create_operational_exception(p_category text,p_severity text,p_urgency text,p_title text,p_description text,p_entity_type text,p_entity_id uuid default null,p_owner_user_id uuid default null,p_evidence jsonb default'[]')returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare v_actor uuid:=auth.uid();v_id uuid;v_task uuid;v_response timestamptz;v_resolution timestamptz;v_priority text;
begin if v_actor is null or not public.is_staff()then raise exception 'Staff access required';end if;if lower(btrim(coalesce(p_category,'')))not in('travel_disruption','supplier','payment','document','security','privacy','integration','data_quality','cross_company','deadline','other')then raise exception 'Invalid exception category';end if;if lower(btrim(coalesce(p_severity,'')))not in('low','medium','high','critical')then raise exception 'Invalid severity';end if;if lower(btrim(coalesce(p_urgency,'')))not in('normal','urgent','immediate')then raise exception 'Invalid urgency';end if;if lower(btrim(coalesce(p_entity_type,'')))not in('booking','enquiry','payment','document','supplier','corporate_desk_case','customer','integration','system','other')then raise exception 'Invalid entity type';end if;if char_length(btrim(coalesce(p_title,'')))not between 3 and 180 then raise exception 'Title must be 3 to 180 characters';end if;if char_length(btrim(coalesce(p_description,'')))not between 10 and 5000 then raise exception 'Description must be 10 to 5000 characters';end if;if jsonb_typeof(coalesce(p_evidence,'[]'))<>'array'then raise exception 'Evidence must be a JSON array';end if;if p_owner_user_id is not null and not exists(select 1 from public.staff_profiles where user_id=p_owner_user_id and active)then raise exception 'Owner must be active staff';end if;if p_entity_id is not null and exists(select 1 from public.operational_exceptions where entity_type=lower(btrim(p_entity_type))and entity_id=p_entity_id and category=lower(btrim(p_category))and status not in('resolved','closed'))then raise exception 'An open exception already exists for this record and category';end if;
 v_response:=now()+case lower(p_urgency)when'immediate'then interval '15 minutes' when'urgent'then interval '2 hours'else interval '1 day'end;v_resolution:=now()+case lower(p_severity)when'critical'then interval '4 hours'when'high'then interval '1 day'when'medium'then interval '3 days'else interval '7 days'end;v_priority:=case lower(p_severity)when'critical'then'urgent'when'high'then'high'when'medium'then'normal'else'low'end;
 insert into public.operational_exceptions(category,severity,urgency,title,description,entity_type,entity_id,owner_user_id,response_due_at,resolution_due_at,evidence,created_by)values(lower(btrim(p_category)),lower(btrim(p_severity)),lower(btrim(p_urgency)),btrim(p_title),btrim(p_description),lower(btrim(p_entity_type)),p_entity_id,p_owner_user_id,v_response,v_resolution,coalesce(p_evidence,'[]'),v_actor)returning id into v_id;
 insert into public.tasks_reminders(title,task_type,entity_type,entity_id,due_at,priority,assigned_to,notes,created_by,automation_key)values('Exception: '||left(btrim(p_title),160),'follow_up','operational_exception',v_id,v_response,v_priority,p_owner_user_id,'Contain, communicate and recover through the Exceptions workspace.',v_actor,'operational-exception:'||v_id)returning id into v_task;update public.operational_exceptions set task_id=v_task where id=v_id;
 insert into public.audit_events(actor_user_id,event_type,entity_type,entity_id,metadata)values(v_actor,'operational_exception.created','operational_exception',v_id,jsonb_build_object('category',lower(p_category),'severity',lower(p_severity),'urgency',lower(p_urgency),'affected_entity_type',lower(p_entity_type),'affected_entity_id',p_entity_id,'owner_user_id',p_owner_user_id,'response_due_at',v_response,'resolution_due_at',v_resolution,'task_id',v_task));return v_id;end$$;

create function public.list_operational_exceptions(p_status text default null,p_limit integer default 300)returns setof public.operational_exceptions language sql stable security definer set search_path=public,pg_temp as $$select x.* from public.operational_exceptions x where public.is_staff()and(p_status is null or x.status=p_status)order by case x.severity when'critical'then 0 when'high'then 1 when'medium'then 2 else 3 end,(x.status not in('resolved','closed')and now()>x.response_due_at)desc,x.created_at desc limit least(greatest(coalesce(p_limit,300),1),500)$$;

create function public.update_operational_exception(p_exception_id uuid,p_status text,p_owner_user_id uuid default null,p_external_update text default null,p_containment text default null,p_recovery_action text default null,p_resolution text default null,p_root_cause text default null,p_preventive_action text default null,p_escalate boolean default false)returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare v_actor uuid:=auth.uid();v_old public.operational_exceptions%rowtype;v_status text:=lower(btrim(coalesce(p_status,'')));
begin if v_actor is null or not public.is_staff()then raise exception 'Staff access required';end if;if v_status not in('open','contained','recovering','waiting_external','resolved','closed')then raise exception 'Invalid status';end if;if p_owner_user_id is not null and not exists(select 1 from public.staff_profiles where user_id=p_owner_user_id and active)then raise exception 'Owner must be active staff';end if;select *into v_old from public.operational_exceptions where id=p_exception_id for update;if not found then raise exception 'Exception not found';end if;if v_status in('resolved','closed')and char_length(btrim(coalesce(p_resolution,v_old.resolution,'')))<10 then raise exception 'Resolution of at least 10 characters is required';end if;
 update public.operational_exceptions set status=v_status,owner_user_id=coalesce(p_owner_user_id,owner_user_id),external_update=coalesce(nullif(btrim(coalesce(p_external_update,'')),''),external_update),containment=coalesce(nullif(btrim(coalesce(p_containment,'')),''),containment),recovery_action=coalesce(nullif(btrim(coalesce(p_recovery_action,'')),''),recovery_action),resolution=coalesce(nullif(btrim(coalesce(p_resolution,'')),''),resolution),root_cause=coalesce(nullif(btrim(coalesce(p_root_cause,'')),''),root_cause),preventive_action=coalesce(nullif(btrim(coalesce(p_preventive_action,'')),''),preventive_action),escalation_level=case when p_escalate then least(escalation_level+1,5)else escalation_level end,escalated_at=case when p_escalate then now()else escalated_at end,contained_at=case when v_status in('contained','recovering','waiting_external','resolved','closed')then coalesce(contained_at,now())else contained_at end,resolved_at=case when v_status in('resolved','closed')then coalesce(resolved_at,now())else null end,updated_at=now()where id=p_exception_id;
 update public.tasks_reminders set assigned_to=coalesce(p_owner_user_id,assigned_to),status=case when v_status in('resolved','closed')then'done'else status end,completed_at=case when v_status in('resolved','closed')then coalesce(completed_at,now())else completed_at end,priority=case when p_escalate then'urgent'else priority end,escalated_at=case when p_escalate then now()else escalated_at end where id=v_old.task_id;
 insert into public.audit_events(actor_user_id,event_type,entity_type,entity_id,metadata)values(v_actor,'operational_exception.updated','operational_exception',p_exception_id,jsonb_build_object('from_status',v_old.status,'to_status',v_status,'owner_user_id',coalesce(p_owner_user_id,v_old.owner_user_id),'escalated',p_escalate,'escalation_level',v_old.escalation_level+case when p_escalate then 1 else 0 end));end$$;

revoke execute on function public.create_operational_exception(text,text,text,text,text,text,uuid,uuid,jsonb)from public,anon;revoke execute on function public.list_operational_exceptions(text,integer)from public,anon;revoke execute on function public.update_operational_exception(uuid,text,uuid,text,text,text,text,text,text,boolean)from public,anon;grant execute on function public.create_operational_exception(text,text,text,text,text,text,uuid,uuid,jsonb)to authenticated;grant execute on function public.list_operational_exceptions(text,integer)to authenticated;grant execute on function public.update_operational_exception(uuid,text,uuid,text,text,text,text,text,text,boolean)to authenticated;
