create table public.corporate_travel_policies (
 id uuid primary key default gen_random_uuid(),corporate_account_id uuid not null references public.corporate_accounts(id) on delete cascade,branch_id uuid references public.corporate_branches(id) on delete cascade,
 policy_name text not null check(char_length(btrim(policy_name)) between 2 and 160),currency text not null default 'AED' check(currency~'^[A-Z]{3}$'),trip_budget_limit numeric(14,2) check(trip_budget_limit is null or trip_budget_limit>=0),
 approval_threshold numeric(14,2) check(approval_threshold is null or approval_threshold>=0),advance_booking_days integer not null default 0 check(advance_booking_days between 0 and 365),
 max_cabin text not null default 'economy' check(max_cabin in ('economy','premium_economy','business','first')),max_hotel_stars integer check(max_hotel_stars between 1 and 5),requires_lpo boolean not null default false,requires_second_approval boolean not null default false,
 status text not null default 'active' check(status in ('draft','active','inactive')),effective_from date not null default current_date,effective_to date,notes text,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(effective_to is null or effective_to>=effective_from)
);
create unique index corporate_policy_company_default_uq on public.corporate_travel_policies(corporate_account_id) where branch_id is null and status<>'inactive';
create unique index corporate_policy_branch_uq on public.corporate_travel_policies(corporate_account_id,branch_id) where branch_id is not null and status<>'inactive';
alter table public.corporate_travel_policies enable row level security;revoke all on public.corporate_travel_policies from anon,authenticated;grant all on public.corporate_travel_policies to service_role;
create or replace function public.list_corporate_travel_policies(p_corporate_account_id uuid default null) returns setof public.corporate_travel_policies language sql stable security definer set search_path=public,pg_temp as $$select p.* from public.corporate_travel_policies p where public.is_staff() and (p_corporate_account_id is null or p.corporate_account_id=p_corporate_account_id) order by p.created_at desc$$;
create or replace function public.list_my_corporate_travel_policies(p_corporate_account_id uuid) returns table(id uuid,branch_id uuid,policy_name text,currency text,trip_budget_limit numeric,approval_threshold numeric,advance_booking_days integer,max_cabin text,max_hotel_stars integer,requires_lpo boolean,requires_second_approval boolean,effective_from date,effective_to date,notes text) language sql stable security definer set search_path=public,pg_temp as $$select p.id,p.branch_id,p.policy_name,p.currency,p.trip_budget_limit,p.approval_threshold,p.advance_booking_days,p.max_cabin,p.max_hotel_stars,p.requires_lpo,p.requires_second_approval,p.effective_from,p.effective_to,p.notes from public.corporate_travel_policies p where p.corporate_account_id=p_corporate_account_id and p.status='active' and current_date>=p.effective_from and (p.effective_to is null or current_date<=p.effective_to) and exists(select 1 from public.corporate_portal_members m where m.user_id=auth.uid() and m.corporate_account_id=p.corporate_account_id and m.status='active') order by p.branch_id nulls first$$;
create or replace function public.save_corporate_travel_policy(p_corporate_account_id uuid,p_branch_id uuid,p_policy_name text,p_currency text,p_trip_budget_limit numeric,p_approval_threshold numeric,p_advance_booking_days integer,p_max_cabin text,p_max_hotel_stars integer,p_requires_lpo boolean,p_requires_second_approval boolean,p_status text,p_effective_from date,p_effective_to date,p_notes text) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$declare v_user uuid:=auth.uid();v_id uuid;begin if v_user is null or not public.has_staff_permission('edit_corporates') then raise exception 'Corporate edit permission required';end if;if p_branch_id is not null and not exists(select 1 from public.corporate_branches b where b.id=p_branch_id and b.corporate_account_id=p_corporate_account_id and b.archived_at is null) then raise exception 'Branch does not belong to company';end if;insert into public.corporate_travel_policies(corporate_account_id,branch_id,policy_name,currency,trip_budget_limit,approval_threshold,advance_booking_days,max_cabin,max_hotel_stars,requires_lpo,requires_second_approval,status,effective_from,effective_to,notes,created_by)values(p_corporate_account_id,p_branch_id,btrim(p_policy_name),upper(p_currency),p_trip_budget_limit,p_approval_threshold,coalesce(p_advance_booking_days,0),p_max_cabin,p_max_hotel_stars,coalesce(p_requires_lpo,false),coalesce(p_requires_second_approval,false),p_status,coalesce(p_effective_from,current_date),p_effective_to,nullif(btrim(coalesce(p_notes,'')),''),v_user)returning id into v_id;insert into public.audit_events(actor_user_id,event_type,entity_type,entity_id,metadata)values(v_user,'corporate_travel_policy_created','corporate_travel_policy',v_id,jsonb_build_object('corporate_account_id',p_corporate_account_id,'branch_id',p_branch_id,'status',p_status));return v_id;end$$;
revoke execute on function public.list_corporate_travel_policies(uuid) from public,anon;revoke execute on function public.list_my_corporate_travel_policies(uuid) from public,anon;revoke execute on function public.save_corporate_travel_policy(uuid,uuid,text,text,numeric,numeric,integer,text,integer,boolean,boolean,text,date,date,text) from public,anon;
grant execute on function public.list_corporate_travel_policies(uuid) to authenticated;grant execute on function public.list_my_corporate_travel_policies(uuid) to authenticated;grant execute on function public.save_corporate_travel_policy(uuid,uuid,text,text,numeric,numeric,integer,text,integer,boolean,boolean,text,date,date,text) to authenticated;
