alter table public.supplier_payments add column if not exists dispute_reference text,add column if not exists dispute_reason text,add column if not exists dispute_previous_status text,add column if not exists dispute_opened_by uuid references auth.users(id) on delete set null,add column if not exists dispute_opened_at timestamptz,add column if not exists dispute_resolved_by uuid references auth.users(id) on delete set null,add column if not exists dispute_resolved_at timestamptz,add column if not exists dispute_resolution text;
create or replace function public.open_supplier_payment_dispute(p_supplier_payment_id uuid,p_reference text,p_reason text) returns jsonb language plpgsql security definer set search_path='public' as $function$
declare v public.supplier_payments%rowtype; begin
 if auth.uid() is null then raise exception 'Authentication required'; end if; perform public.require_recent_auth(1800); if not public.has_staff_permission('edit_payments') then raise exception 'Permission denied'; end if;
 if nullif(trim(coalesce(p_reference,'')),'') is null or char_length(trim(coalesce(p_reason,'')))<10 then raise exception 'Dispute reference and reason of at least 10 characters are required'; end if;
 select * into v from public.supplier_payments where id=p_supplier_payment_id for update; if not found then raise exception 'Supplier payment not found'; end if; if v.status not in('pending','partial') then raise exception 'Only pending or partial payables can be disputed'; end if;
 update public.supplier_payments set dispute_previous_status=v.status,status='disputed',dispute_reference=trim(p_reference),dispute_reason=trim(p_reason),dispute_opened_by=auth.uid(),dispute_opened_at=now(),dispute_resolved_by=null,dispute_resolved_at=null,dispute_resolution=null,updated_at=now() where id=v.id;
 insert into public.audit_events(actor_user_id,event_type,entity_type,entity_id,metadata) values(auth.uid(),'supplier_payment.dispute_opened','supplier_payment',v.id,jsonb_build_object('reference',trim(p_reference),'reason',trim(p_reason),'amount_payable',v.amount_payable,'amount_paid',v.amount_paid,'previous_status',v.status)); return jsonb_build_object('id',v.id,'status','disputed'); end;$function$;
create or replace function public.resolve_supplier_payment_dispute(p_supplier_payment_id uuid,p_resolution text,p_note text) returns jsonb language plpgsql security definer set search_path='public' as $function$
declare v public.supplier_payments%rowtype; v_status text; begin
 if auth.uid() is null then raise exception 'Authentication required'; end if; perform public.require_recent_auth(1800); if not public.is_admin() then raise exception 'Owner or admin resolution required'; end if;
 if p_resolution not in('release','cancel') or char_length(trim(coalesce(p_note,'')))<10 then raise exception 'Resolution must be release or cancel with a note of at least 10 characters'; end if;
 select * into v from public.supplier_payments where id=p_supplier_payment_id for update; if not found or v.status<>'disputed' then raise exception 'Open supplier dispute not found'; end if; if v.dispute_opened_by=auth.uid() then raise exception 'Dispute opener cannot resolve the same dispute'; end if;
 v_status:=case when p_resolution='cancel' then 'cancelled' when v.amount_paid>0 then 'partial' else 'pending' end;
 update public.supplier_payments set status=v_status,dispute_resolution=p_resolution,dispute_resolved_by=auth.uid(),dispute_resolved_at=now(),notes=case when notes is null then trim(p_note) else notes||E'\n'||trim(p_note) end,updated_at=now() where id=v.id;
 insert into public.audit_events(actor_user_id,event_type,entity_type,entity_id,metadata) values(auth.uid(),'supplier_payment.dispute_resolved','supplier_payment',v.id,jsonb_build_object('opener_user_id',v.dispute_opened_by,'resolution',p_resolution,'resulting_status',v_status,'note',trim(p_note))); return jsonb_build_object('id',v.id,'status',v_status,'resolution',p_resolution); end;$function$;
revoke execute on function public.open_supplier_payment_dispute(uuid,text,text) from public,anon;grant execute on function public.open_supplier_payment_dispute(uuid,text,text) to authenticated,service_role;
revoke execute on function public.resolve_supplier_payment_dispute(uuid,text,text) from public,anon;grant execute on function public.resolve_supplier_payment_dispute(uuid,text,text) to authenticated,service_role;
