begin;
create function public.management_control_dashboard(p_start date,p_end date)returns jsonb language plpgsql stable security definer set search_path=public,pg_temp as $$
declare v_actor uuid:=auth.uid();v_enquiries numeric;v_booked numeric;v_sales numeric;v_cost numeric;v_can_profit boolean;v_result jsonb;
begin
 if v_actor is null or not public.has_staff_permission('view_reports')then raise exception'Report permission required';end if;
 if p_start is null or p_end is null or p_end<p_start or p_end-p_start>366 then raise exception'Invalid dashboard period';end if;
 v_can_profit:=public.has_staff_permission('view_profit');
 select count(*),count(*)filter(where booking_confirmed_at is not null)into v_enquiries,v_booked from public.enquiries where created_at::date between p_start and p_end;
 select coalesce(sum(coalesce(selling_price,amount,0)),0),coalesce(sum(coalesce(supplier_cost,0)),0)into v_sales,v_cost from public.bookings where archived_at is null and created_at::date between p_start and p_end;
 v_result:=jsonb_build_object('period_start',p_start,'period_end',p_end,'generated_at',now(),
 'sla',jsonb_build_object('enquiries',v_enquiries,'responded',(select count(*)from public.enquiries where created_at::date between p_start and p_end and first_response_at is not null),'within_sla',(select count(*)from public.enquiries where created_at::date between p_start and p_end and first_response_at is not null and first_response_at<=sla_first_response_due_at),'overdue_now',(select count(*)from public.enquiries where first_response_at is null and status<>'closed'and sla_first_response_due_at<now()),'compliance_percent',case when v_enquiries=0 then 0 else round((select count(*)from public.enquiries where created_at::date between p_start and p_end and first_response_at is not null and first_response_at<=sla_first_response_due_at)*100.0/v_enquiries,2)end),
 'conversion',jsonb_build_object('enquiries',v_enquiries,'confirmed',v_booked,'conversion_percent',case when v_enquiries=0 then 0 else round(v_booked*100/v_enquiries,2)end,'lost',(select count(*)from public.enquiries where created_at::date between p_start and p_end and lost_reason is not null),'by_source',(select coalesce(jsonb_agg(to_jsonb(x)order by x.enquiries desc),'[]')from(select coalesce(first_touch_source,'unknown')source,count(*)enquiries,count(*)filter(where booking_confirmed_at is not null)confirmed from public.enquiries where created_at::date between p_start and p_end group by 1 limit 20)x)),
 'margin',case when v_can_profit then jsonb_build_object('sales',v_sales,'supplier_cost',v_cost,'gross_margin',v_sales-v_cost,'margin_percent',case when v_sales=0 then 0 else round((v_sales-v_cost)*100/v_sales,2)end,'negative_margin_bookings',(select count(*)from public.bookings where archived_at is null and created_at::date between p_start and p_end and coalesce(selling_price,amount,0)<coalesce(supplier_cost,0)))else jsonb_build_object('restricted',true)end,
 'workload',jsonb_build_object('open_tasks',(select count(*)from public.tasks_reminders where status<>'done'),'overdue_tasks',(select count(*)from public.tasks_reminders where status<>'done'and due_at<now()),'unassigned_tasks',(select count(*)from public.tasks_reminders where status<>'done'and assigned_to is null),'by_owner',(select coalesce(jsonb_agg(to_jsonb(x)order by x.open_tasks desc),'[]')from(select assigned_to,count(*)open_tasks,count(*)filter(where due_at<now())overdue from public.tasks_reminders where status<>'done'group by assigned_to limit 30)x)),
 'suppliers',jsonb_build_object('active',(select count(*)from public.suppliers where status='active'),'payable_balance',(select coalesce(sum(amount_payable-amount_paid),0)from public.supplier_payments),'overdue_payments',(select count(*)from public.supplier_payments where amount_paid<amount_payable and due_date<current_date),'open_disputes',(select count(*)from public.supplier_payments where dispute_opened_at is not null and dispute_resolved_at is null),'largest_balances',(select coalesce(jsonb_agg(to_jsonb(x)order by x.balance desc),'[]')from(select coalesce(s.name,sp.supplier_name,'Unknown')supplier,sum(sp.amount_payable-sp.amount_paid)balance,count(*)filter(where sp.amount_paid<sp.amount_payable and sp.due_date<current_date)overdue_count from public.supplier_payments sp left join public.suppliers s on s.id=sp.supplier_id group by 1 order by 2 desc limit 20)x)),
 'exceptions',jsonb_build_object('open',(select count(*)from public.operational_exceptions where status not in('resolved','closed')),'critical_high',(select count(*)from public.operational_exceptions where status not in('resolved','closed')and severity in('critical','high')),'overdue_response',(select count(*)from public.operational_exceptions where status not in('resolved','closed')and response_due_at<now()),'overdue_resolution',(select count(*)from public.operational_exceptions where status not in('resolved','closed')and resolution_due_at<now()),'by_category',(select coalesce(jsonb_agg(to_jsonb(x)order by x.open_count desc),'[]')from(select category,count(*)open_count from public.operational_exceptions where status not in('resolved','closed')group by category)x)),
 'reconciliation',jsonb_build_object('open_cases',(select count(*)from public.financial_reconciliation_cases where status in('open','investigating')),'critical_high',(select count(*)from public.financial_reconciliation_cases where status in('open','investigating')and severity in('critical','high')),'overdue',(select count(*)from public.financial_reconciliation_cases where status in('open','investigating')and due_at<now())));
 return v_result;
end$$;
revoke execute on function public.management_control_dashboard(date,date)from public,anon;grant execute on function public.management_control_dashboard(date,date)to authenticated,service_role;
commit;
