begin;
create table public.financial_reconciliation_cases(
 id uuid primary key default gen_random_uuid(),snapshot_id uuid not null references public.management_report_snapshots(id)on delete restrict,
 reconciliation_type text not null check(reconciliation_type in('customer_money','supplier_money','refunds','corporate_statement')),
 status text not null default'open' check(status in('open','investigating','resolved','accepted_exception')),
 expected_amount numeric not null default 0,recorded_amount numeric not null default 0,variance numeric generated always as(expected_amount-recorded_amount)stored,
 currency text not null default'AED',severity text not null check(severity in('low','medium','high','critical')),owner_user_id uuid not null references auth.users(id),due_at timestamptz not null,
 explanation text,resolution_evidence text,final_variance numeric,task_id uuid references public.tasks_reminders(id),created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),resolved_at timestamptz
);
create unique index financial_reconciliation_open_uidx on public.financial_reconciliation_cases(snapshot_id,reconciliation_type)where status in('open','investigating');
create index financial_reconciliation_queue_idx on public.financial_reconciliation_cases(status,severity,due_at);
alter table public.financial_reconciliation_cases enable row level security;revoke all on public.financial_reconciliation_cases from public,anon,authenticated;grant all on public.financial_reconciliation_cases to service_role;

create function public.scan_financial_reconciliation(p_snapshot_id uuid,p_tolerance numeric default 0.01)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare v_actor uuid:=auth.uid();v_s public.management_report_snapshots%rowtype;v_owner uuid;v_created integer:=0;v_item record;v_id uuid;v_task uuid;begin if v_actor is null or not public.has_staff_permission('view_reports')then raise exception'Report permission required';end if;if p_tolerance<0 or p_tolerance>1000000 then raise exception'Invalid tolerance';end if;select*into v_s from public.management_report_snapshots where id=p_snapshot_id;if not found then raise exception'Report snapshot not found';end if;select sr.user_id into v_owner from public.staff_roles sr join public.staff_profiles sp on sp.user_id=sr.user_id and sp.active where sr.role::text='owner'order by sr.created_at limit 1;v_owner:=coalesce(v_owner,v_actor);
for v_item in select*from(values('customer_money',coalesce((v_s.reconciliation->>'booking_sales')::numeric,0)-coalesce((v_s.reconciliation->>'approved_or_paid_refunds')::numeric,0),coalesce((v_s.reconciliation->>'customer_money_received')::numeric,0)),('supplier_money',coalesce((v_s.reconciliation->>'booking_supplier_cost')::numeric,0),coalesce((v_s.reconciliation->>'supplier_payables')::numeric,0)),('refunds',coalesce((v_s.reconciliation->>'approved_or_paid_refunds')::numeric,0),coalesce((v_s.payload->>'refunds')::numeric,coalesce((v_s.reconciliation->>'approved_or_paid_refunds')::numeric,0))),('corporate_statement',case when v_s.report_type='corporate'then coalesce((v_s.payload->>'corporate_booking_value')::numeric,0)else 0 end,case when v_s.report_type='corporate'then coalesce((v_s.reconciliation->>'booking_sales')::numeric,0)else 0 end))x(kind,expected,recorded)where abs(expected-recorded)>p_tolerance loop
 insert into public.financial_reconciliation_cases(snapshot_id,reconciliation_type,expected_amount,recorded_amount,severity,owner_user_id,due_at,created_by)values(p_snapshot_id,v_item.kind,v_item.expected,v_item.recorded,case when abs(v_item.expected-v_item.recorded)>=10000 then'critical'when abs(v_item.expected-v_item.recorded)>=1000 then'high'when abs(v_item.expected-v_item.recorded)>=100 then'medium'else'low'end,v_owner,now()+case when abs(v_item.expected-v_item.recorded)>=10000 then interval'4 hours'when abs(v_item.expected-v_item.recorded)>=1000 then interval'1 day'else interval'3 days'end,v_actor)on conflict(snapshot_id,reconciliation_type)where status in('open','investigating')do nothing returning id into v_id;if v_id is not null then insert into public.tasks_reminders(title,task_type,entity_type,entity_id,due_at,status,priority,assigned_to,notes,created_by,automation_key)select'Reconcile '||replace(v_item.kind,'_',' '),'follow_up','financial_reconciliation',v_id,due_at,'open',case severity when'critical'then'urgent'when'high'then'high'else'normal'end,v_owner,'Resolve against canonical transaction evidence; do not adjust totals only to clear the variance.',v_actor,'financial-reconciliation:'||v_id from public.financial_reconciliation_cases where id=v_id returning id into v_task;update public.financial_reconciliation_cases set task_id=v_task where id=v_id;v_created:=v_created+1;end if;v_id:=null;end loop;insert into public.audit_events(actor_user_id,event_type,entity_type,entity_id,metadata)values(v_actor,'financial_reconciliation.scanned','management_report_snapshot',p_snapshot_id,jsonb_build_object('tolerance',p_tolerance,'cases_created',v_created));return jsonb_build_object('cases_created',v_created);end$$;
create function public.list_financial_reconciliation_cases(p_status text default null,p_limit integer default 200)returns jsonb language sql stable security definer set search_path=public,pg_temp as $$select case when public.has_staff_permission('view_reports')then coalesce(jsonb_agg(to_jsonb(x)order by x.created_at desc),'[]')else'[]'::jsonb end from(select c.*,s.report_type,s.period_start,s.period_end from public.financial_reconciliation_cases c join public.management_report_snapshots s on s.id=c.snapshot_id where p_status is null or c.status=p_status order by case c.severity when'critical'then 0 when'high'then 1 else 2 end,c.due_at limit least(greatest(coalesce(p_limit,200),1),500))x$$;
create function public.resolve_financial_reconciliation(p_case_id uuid,p_status text,p_explanation text,p_resolution_evidence text,p_final_variance numeric)returns void language plpgsql security definer set search_path=public,pg_temp as $$declare v_actor uuid:=auth.uid();v_old public.financial_reconciliation_cases%rowtype;v_status text:=lower(btrim(coalesce(p_status,'')));begin if v_actor is null or not public.is_admin()then raise exception'Owner/admin access required';end if;if v_status not in('investigating','resolved','accepted_exception')then raise exception'Invalid status';end if;select*into v_old from public.financial_reconciliation_cases where id=p_case_id for update;if not found then raise exception'Case not found';end if;if v_status in('resolved','accepted_exception')and(char_length(btrim(coalesce(p_explanation,'')))<10 or char_length(btrim(coalesce(p_resolution_evidence,'')))<10 or p_final_variance is null)then raise exception'Closure explanation, evidence and final variance are required';end if;if v_status='resolved'and abs(p_final_variance)>0.01 then raise exception'Resolved cases must reconcile within tolerance; use accepted exception with evidence otherwise';end if;update public.financial_reconciliation_cases set status=v_status,explanation=nullif(btrim(coalesce(p_explanation,'')),''),resolution_evidence=nullif(btrim(coalesce(p_resolution_evidence,'')),''),final_variance=p_final_variance,resolved_at=case when v_status in('resolved','accepted_exception')then now()else null end,updated_at=now()where id=p_case_id;update public.tasks_reminders set status=case when v_status in('resolved','accepted_exception')then'done'else status end,completed_at=case when v_status in('resolved','accepted_exception')then now()else completed_at end where id=v_old.task_id;insert into public.audit_events(actor_user_id,event_type,entity_type,entity_id,metadata)values(v_actor,'financial_reconciliation.updated','financial_reconciliation',p_case_id,jsonb_build_object('from_status',v_old.status,'to_status',v_status,'final_variance',p_final_variance));end$$;
revoke execute on function public.scan_financial_reconciliation(uuid,numeric),public.list_financial_reconciliation_cases(text,integer),public.resolve_financial_reconciliation(uuid,text,text,text,numeric)from public,anon;grant execute on function public.scan_financial_reconciliation(uuid,numeric),public.list_financial_reconciliation_cases(text,integer),public.resolve_financial_reconciliation(uuid,text,text,text,numeric)to authenticated,service_role;
commit;
